language: bash
sudo: false
install: true
branches:
  only: master

before_install:
- |-
  if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
    TRAVIS_COMMIT_RANGE="FETCH_HEAD...$TRAVIS_BRANCH"
  fi
  git diff --name-only $TRAVIS_COMMIT_RANGE | grep --quiet '^data$' || {
    echo no changes to DNS records
    exit
  }

after_success:
- openssl aes-256-cbc -K $encrypted_aa75ac26308c_key -iv $encrypted_aa75ac26308c_iv
  -in .ssh/id_rsa.enc -out .ssh/id_rsa -d
- cp -r .ssh ~/
- chmod -R u=rwX,go= ~/.ssh
- |-
  grep '^\.' data | cut -f2 -d: | sort -u | xargs --no-run-if-empty --max-lines=1 --replace=% ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=QUIET %
